name: Generate VPN Config
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install and Run Warp-Reg
        run: |
          curl -sSL https://github.com/ViRb3/wg-cf-v2/releases/latest/download/wg-cf-v2_linux_amd64 -o wg-cf-v2
          chmod +x wg-cf-v2
          ./wg-cf-v2 --register
      - name: Upload Config
        uses: actions/upload-artifact@v4
        with:
          name: vpn-config
          path: wg-config.conf
